### ISSUE TITLE
gphoto 2.5.5.1 is released

### ISSUE THREAD

**Issue by duststorm** [gonzalo/gphoto2-updater#12]
Meanwhile libgphoto 2.5.5.1 with a few regression fixes is released. It might be interesting to update.
```
Changelog:
libgphoto2 2.5.5.1 release

This is a regression fix release for 2.5.5..

ptp2:
* fixed all Nikon S* coolpix that are not Nikon 1
* Nikon: exit from potential endless loop on trigger capture

canon:
* On EOS/Rebel DSLR do not query or set "zoom" as its manual always

translations:
* updated polish, ukrainian, vietnamese
```

Tarball can be found at: http://sourceforge.net/projects/gphoto/files/libgphoto/2.5.5.1/

**Comment by gonzalo** [comment]
Thanks to @mpneuried we have a new updated version to 2.5.6.

Thanks for your notification anyway.
