### ISSUE TITLE
Make tag for each gphoto version

### ISSUE THREAD

**Issue by Sija** [gonzalo/gphoto2-updater#14]
It would be much helpful when trying to install given gphoto version. Then we could use `https://raw.githubusercontent.com/gonzalo/gphoto2-updater/[v2.5.5]/gphoto2-updater.sh` url form. Otherwise we need to resort to using commit SHA.

Thanks for consideration and for such a helpful project :)

**Comment by gonzalo** [comment]
That sounds cool! I have never used before git tags. I'll give it a try in future developments.

Thanks for your feedback!

**Comment by Sija** [comment]
No problem, this script saved me some time during development and that motivates :) For tag/release management you can use fine [github web ui](https://github.com/gonzalo/gphoto2-updater/releases/new), retroactively too (`v2.5.5` plz?) :)

**Comment by gonzalo** [comment]
Nice! yesteday I was looking about tags but I get stuck about how to do it from web UI. Let me take a look to do it

**Comment by gonzalo** [comment]
Here you will find 2.5.5 version https://github.com/gonzalo/gphoto2-updater/releases/tag/2.5.5

...and obviously lastest version is https://github.com/gonzalo/gphoto2-updater/releases/latest

Thank you for introducing me to tags and releases in GIT

**Comment by Sija** [comment]
Swell news, thanks! :)
