### ISSUE TITLE
libgphoto2 >= 2.5.6 not met. Found: 2.4.14

### ISSUE THREAD

**Issue by Xophe92** [gonzalo/gphoto2-updater#16]
Hi, 

I used the following command line :  wget https://github.com/gonzalo/gphoto2-updater/releases/download/2.5.7/gphoto2-updater.sh && chmod +x gphoto2-updater.sh && sudo ./gphoto2-updater.sh

during the "make" of libgphoto2 I guess, I obtain a first error message:

Then  I get 
checking if libgphoto2 version is matching requirement >= 2.5.6... no
configure: error: Version requirement libgphoto2 >= 2.5.6 not met. Found: 2.4.14

I deleted "/usr/local/lib/libgphoto*" and started again and made sure that nothing was linked to gphoto in /usr/lib...

Please advice on to proceed

Regards,

Christophe

**Comment by gonzalo** [comment]
"sudo apt-get remove libgphoto2" is probably the best way to do it

**Comment by gonzalo** [comment]
Also I recommend to download new gphoto2-updater version wich fix a 404 error when trying to dowlad libusbx_1.0.17
