### ISSUE TITLE
Unable to get libusbx_1.0.17

### ISSUE THREAD

**Issue by Benjamin7785** [gonzalo/gphoto2-updater#25]
The script aborts throwing the error "unable to get libusbx_1.0.17"

**Comment by scribblemaniac** [comment]
Please make sure you have the most updated version of the script. We are no longer even using libusbx 1.0.17. If you continue to get this error after updating the script, please post an actually copy of the output.

**Comment by gonzalo** [comment]
Current master branch has been updated to libusbx 1.0.18
Next version will be updated to libusb 1.0.20 https://github.com/gonzalo/gphoto2-updater/tree/GitHub-integration
