### ISSUE TITLE
autopoint is missing

### ISSUE THREAD

**Issue by fernandocasar** [gonzalo/gphoto2-updater#32]
Script was failing, after 'apt-get install autopoint' it worked. This was in ubuntu 14.04.2

**Comment by scribblemaniac** [comment]
Looks like we are missing a few dependencies for installing from the git repo:
[Step 0: Preparing Configuration](https://github.com/gphoto/libgphoto2/blob/master/INSTALL#L21)

I don't see autopoint, gettext, or libtool in the list of packages we install. Also automake is being checked twice for some reason.
