### ISSUE TITLE
Problems with sh file

### ISSUE THREAD

**Issue by raffaelecolleo** [gonzalo/gphoto2-updater#35]
Hi Gonzalo,
I'm having problems installing the libraries on a raspberri pi 2.
I have the lite version of jessie installed and cannot install libgphoto2. 
line 141: git: command not found.

There is also a problem on libusb 1.0.20
tar: Child returned status 2
tar: Error is not recoverable: exiting now.

Could You please check this errors

Thanks a lot

**Comment by gonzalo** [comment]
That's very strange because git package should be installed at the beginning of script.

Please check that you have git installed (git -v) and if not install it manually with "sudo apt-get install git" and try again.

**Comment by gonzalo** [comment]
Hi @raffaelecolleo ! any updates about this issue?

**Comment by gonzalo** [comment]
Closed by inactivity
