### ISSUE TITLE
libusb 1 confusion

### ISSUE THREAD

**Issue by msmeissn** [gonzalo/gphoto2-updater#36]
can you perhaps try to use the system libusb 1 ...? 

building a different libusb 1 version than the one on system, but using them causes reports where
libusb_strerror is missing

libusb-1.0-0-dev

is the ubuntu packagename for the development files I think.

**Comment by gonzalo** [comment]
Hi @msmeissn , not sure why I'm using libusb 1.0.20, probably it was a kind of requierement when I began this project.

I'll give a try to system library libusb-dev and check if libgphoto2 and ghoto2 compile right

**Comment by gonzalo** [comment]
After testing it in Debian Jeezy / Wheezy, Ubuntu 14.04 and Raspian 7 / 8, use of system libusb dev package seems to work correctly. Compilation works fine.

Change pushed to the master branch
