### ISSUE TITLE
Rollback to a previous version?

### ISSUE THREAD

**Issue by Nic2012** [gonzalo/gphoto2-updater#40]
How can I use the script to install one of the previous versions e.g. 2.5.7 ?

Thank y for y effort providing us this batch :)
Best regards,
Nic

**Comment by gonzalo** [comment]
Check different releases at https://github.com/gonzalo/gphoto2-updater/releases

**Comment by Nic2012** [comment]
Hmmh, its a bit confusing, each paragraph of previous version describes same link to the current update script:
..
Gphoto2 and libgphoto2 2.5.7 compiler and installer script
http://github.com/gonzalo/gphoto2-updater...
..
You probably meant the part under downloads?

**Comment by scribblemaniac** [comment]
Yes, it's the downloads you want, not that link.

**Comment by gonzalo** [comment]
Each realease attaches below paragraph the source code of tht release

**Comment by Nic2012** [comment]
BTW the new 2.5.10 is out, according to release notes there is bugfix that could help me. That was the reason why I wanted to rollback. Do y have plans to upgrade the updater :)

**Comment by gonzalo** [comment]
By default, the master branch offers the possibility of installing lastest development version (at this moment 2.5.10.1). 

Anyway soon I will publish a new version including lastets stable version 2.5.10.

**Comment by gonzalo** [comment]
New version of script for 2.5.10 is available

**Comment by Nic2012** [comment]
Great!
Update to 2.5.10 works fine. Thank y very much.
