### ISSUE TITLE
Unable to get libgphoto2-2.5.9

### ISSUE THREAD

**Issue by benoitguigal** [gonzalo/gphoto2-updater#43]
I got this error last time I ran the script

**Comment by scribblemaniac** [comment]
Libgphoto2 2.5.9 is not the version downloaded by the latest version of our script. Please make sure that you have the latest version of our script and try again. If the error occurs again, please copy the full output here.

**Comment by benoitguigal** [comment]
It is working with the last release. Thanks !

**Comment by scribblemaniac** [comment]
You're welcome!
