### ISSUE TITLE
cannot download and install

### ISSUE THREAD

**Issue by OliverGruenberg** [gonzalo/gphoto2-updater#56]
Hi there,

on my Raspberry Pi 3B instead of simply installing I get this message:

***
-------------------------
Creating temporary folder
-------------------------
gphoto2-temp-folder created
----------------------
Downloading libgphoto2
----------------------
Please run git without sudo, your regular user account is enough :)
Unable to get libgphoto2
Exiting...
***

So... what can I do here?

**Comment by bdonizetisilva** [comment]
Try this command, maybe it works for you:

wget https://raw.githubusercontent.com/gonzalo/gphoto2-updater/master/gphoto2-updater.sh && chmod +x gphoto2-updater.sh && ./gphoto2-updater.sh
