### ISSUE TITLE
Updater hangs

### ISSUE THREAD

**Issue by rnlgreen** [gonzalo/gphoto2-updater#62]
I've tried this a couple of times, it just seems to hang half way through the operation...  not sure what to try?

I get to:
-----------------------------------
Compiling and installing libgphoto2
-----------------------------------

and it copies a bunch of files until it gets to this one then stops:

Copying file po/remove-potcdate.sin

There doesn't appear to be any CPU, disk or network activity at this point.

**Comment by gonzalo** [comment]
This seems related to your own computer. No more feedback regarded about this topic. I will just close it
