### ISSUE TITLE
Always get version 2.5.12 of libphoto2

### ISSUE THREAD

**Issue by Seeelefant** [gonzalo/gphoto2-updater#70]
Dear gonzalo,
I try to use your ghoto2-updater on a Raspberry Pi 3B, but with whatever option I run your script I always get

```
pi@raspberrypi:~ $ gphoto2 --version
gphoto2 2.5.20.1

Copyright (C) 2000-2019 Lutz Müller und andere

gphoto2 comes with NO WARRANTY, to the extent permitted by law. You may
redistribute copies of gphoto2 under the terms of the GNU General Public
License. For more information about these matters, see the files named COPYING.

Diese Version von gphoto2 benutzt die folgenden Softwareversionen und Optionen:
gphoto2         2.5.20.1       gcc, popt(m), exif, no cdk, no aa, no jpeg, no readline
libgphoto2      2.5.12         all camlibs, gcc, ltdl, EXIF
libgphoto2_port 0.12.0         gcc, ltdl, USB, serial without locking
pi@raspberrypi:~ $ 
```

For my camera I need 2.5.21.1 or later libgphoto2 .

Please advice 
--Seeelefant

**Comment by gonzalo** [comment]
Probably relates to #69 Tried the script and got version 2.5.15 

> Your issue is probably because you have another version of gphoto2 installed (ex. from apt). This script used to run apt-get remove gphoto2 libgphoto2*, but does not anymore because it caused the removal of important packages for some users. You can try and use this command to fix your issues, but just check to make sure it doesn't remove something like ubuntu-desktop. It will ask for a confirmation first before doing anything.

**Comment by Seeelefant** [comment]
Dear gonzalo,
now I found that Raspbian comes with libphoto2 in the /usr/lib/arm-linux-gnueabihf/ directory, so building ghoto2 from sources with  --libdir= /usr/lib/arm-linux-gnueabihf/ fixes this problem. Maybe you can incorperate this in your update script.
Best
--Seeelefant

**Comment by unix0r** [comment]
Uninstalling libgphoto2 is another option.
`sudo apt purge libgphoto2 -y`

**Comment by nadre** [comment]
When I try to purge libgphoto2 on my raspy I get an 'Unable to locate package' error. Is there any other way to uninstall?

**Comment by Heinnn** [comment]
> Dear gonzalo,
> now I found that Raspbian comes with libphoto2 in the /usr/lib/arm-linux-gnueabihf/ directory, so building ghoto2 from sources with --libdir= /usr/lib/arm-linux-gnueabihf/ fixes this problem. Maybe you can incorperate this in your update script.
> Best
> --Seeelefant

Hi Seeelefant

I still stuck in the libgphoto2 2.5.12 as your problem.
Can you tell me the step to solve this thing?
I need to update to 2.5.22

Thanks

**Comment by Seeelefant** [comment]
Hi Heinnn,
you have to build libphoto2  as described there from the sources with the option --libdir= /usr/lib/arm-linux-gnueabihf/
Best
--Seeelefant

**Comment by tobiasschuerg** [comment]
Created a PR which is working on my Raspberry 3.
